apiVersion: v1
kind: Service
metadata:
  name: pa234-hw3-570943-service
  namespace: bezrukov-ns
spec:
  selector:
    # Make sure these match the labels on your PHP pod
    app: pa234-hw3-570943  # Adjust based on your actual pod labels
  ports:
    - port: 80
      targetPort: 80  # Assuming Apache is listening on port 80
  type: ClusterIP