uco: "570943"
apiVersion: apps/v1
kind: Deployment

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: 570943-pa234.dyn.cloud.e-infra.cz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: 570943-tls
      hosts:
        - 570943-pa234.dyn.cloud.e-infra.cz

service:
  port: 80      

tenant:
  tenant:
    name: myminio
    pools:
      - servers: 1
        name: pool-0
        volumesPerServer: 1
        storageClassName: nfs-csi
        size: 10Gi
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
          runAsNonRoot: true
        containerSecurityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
    buckets:
      - name: '570943'
    users:
      - name: s3-creds
    certificate:
      requestAutoCert: false
s3:
  access_key: "token-mntmv"
  secret_key: "8fj9dd6l6xsvd4mw6gbzlrgr2lfhbfq562rqqlt45l7ftcfgbg4l27"
  
host: 570943-pa234.dyn.cloud.e-infra.czs
image: cerit.io/pa234/php:8.2-apache
 
db:
  instances: 1
  name: "db-570943"
  owner: "570943"
  resources:
    requests:
      cpu: 1
      memory: "4Gi"
    limits:
      cpu: 1
      memory: "4Gi"
  storage:
    size: 10Gi
    storageClass: nfs-csi
  backup:
    enable: true
    path: "s3://570943/"
    url: "http://minio"

  